---
- hosts: jenkins
  become: true

  plugins:
  - 'ldap'
  - 'github'
  - 'translation'
  - 'preSCMbuildstep'
  - 'gravatar'
    
  tasks: 
  - name: Install key
    rpm_key:
      state: present
      key:  https://jenkins-ci.org/redhat/jenkins-ci.org.key
    
  - name: Add and install RPM for Repo
    get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo

  - name: Install Java
    yum: name=java-1.7.0-openjdk state=latest
    
  - name: Install Jenkins
    yum: name=jenkins state=latest
    register: jenkins_install
  
  - name: Install Git
    yum: name=git state=latest
    
  - name: Install cUrl
    yum: name=curl state=latest
    
  - name: Ensure Jenkins is running
    service:
      name: jenkins
      state: started
    
  - name: Start Jenkins on boot
    shell: chkconfig jenkins on    