---
- hosts: nexus
  become: true
  
  vars:
  
  tasks:   
  - name: Install Java
    yum: name=java-1.7.0-openjdk state=latest
    
  - name: Install unzip
    yum: name=unzip state=latest
    
  - name: Download Nexus 3
    get_url: url=https://sonatype-download.global.ssl.fastly.net/nexus/3/nexus-3.0.2-02-unix.tar.gz dest=/nexus-3.0.2-02-unix.tar.gz  
    
  - name: Create Nexus extraction folder
    file: path=/nexus3 state=directory mode=7777
    
  - name: Extract Nexus
    unarchive: src=/nexus-3.0.2-02-unix.tar.gz dest=/nexus3 remote_src=true