---
- hosts: vault
  become: true
  
  vars:
  
  tasks:
    
  - name: Install unzip
    yum: name=unzip state=latest
    
  - name: Install MariaDB
    yum: name=mariadb-server state=latest    
  
  - name: Download Vault
    get_url: url=https://releases.hashicorp.com/vault/0.6.5/vault_0.6.5_linux_amd64.zip dest=/vault_0.6.5_linux_amd64.zip  
    
  - name: Create Vault extraction folder
    file: path=/vault state=directory mode=7777
    
  - name: Extract Vault
    unarchive: src=/vault_0.6.5_linux_amd64.zip dest=/vault remote_src=true
    
    # Define file path
  - name: Set remote file path here
    set_fact: remote_file_path=/vault/vault.conf    
 
  - name: Remove configuration file
    shell: rm {{ remote_file_path }}
    
    # Create a blank file
  - name: Create a new file
    file: path="{{ remote_file_path }}" state=touch
  
    # Check remote file
  - stat: path="{{ remote_file_path }}"
    register: file_path
  
    # Write file content in file_content variable
  - set_fact: file_content='backend "mysql" {\nusername = "root"\n password="password123"\n}'
  
    # If file exist then copy content in remote file.
  - copy: content="{{ file_content }}" dest="{{ remote_file_path }}"
    when: file_path.stat.exists == true
     
  - name: Ensure MariaDB is running
    service:
      name: mariadb
      state: started

  - name: Ensure MariaDB on started
    shell: systemctl enable mariadb  
    
  - name: Set DB Root PASSWORD
    shell: mysqladmin -u root password "password123"
    
  - name: Update Root Password in DB
    shell: mysql -u root -p"password123" -e "UPDATE mysql.user SET Password=PASSWORD('password123') WHERE User='root'"

  - name: Restrict root login
    shell: mysql -u root -p"password123" -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')"
    
  - name: Drop all non-root users
    shell: mysql -u root -p"password123" -e "DELETE FROM mysql.user WHERE User=''"
    
  - name: Drop test database
    shell: mysql -u root -p"password123" -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'"
    
  - name: FLUSH
    shell: mysql -u root -p"password123" -e "FLUSH PRIVILEGES"    